export const formFieldValues = {
  name: {
    name: 'name',
    type: 'text',
    required: true,
    placeholder: 'Steve Johnson',
    label: 'Full name',
  },
  email: {
    name: 'email',
    type: 'email',
    required: true,
    placeholder: 'steve@plistings.io',
    label: 'Email',
  },
  password: {
    name: 'password',
    type: 'password',
    required: true,
    placeholder: 'Password',
    label: 'Password',
  },
  passwordConfirm: {
    name: 'passwordConfirm',
    type: 'password',
    required: true,
    placeholder: 'Confirm Password',
    label: 'Confirm Password',
  },
  currentPassword: {
    name: 'currentPassword',
    type: 'password',
    required: true,
    placeholder: 'Current Password',
    label: 'Current Password',
  },
  photo: {
    name: 'photo',
    type: 'file',
    required: false,
  },
  bio: {
    name: 'bio',
    placeholder: 'Tell us about yourself',
    label: 'Bio',
    required: false,
  },
  title: {
    name: 'title',
    placeholder: 'What are you selling?',
    label: 'Title',
    required: true,
  },
  price: {
    name: 'price',
    placeholder: 'Set a competitive price',
    label: 'Price',
    type: 'number',
    min: '0',
    step: '.01',
    required: true,
  },
  description: {
    name: 'description',
    placeholder: 'Describe what you are selling, in detail',
    label: 'Description',
    required: false,
  },
  brand: {
    name: 'brand',
    placeholder: 'What is the brand of your item?',
    label: 'Brand',
    required: false,
  },
  minPrice: {
    name: 'minPrice',
    placeholder: '$5',
    label: 'Min Price',
    type: 'number',
    min: '0',
  },
  maxPrice: {
    name: 'maxPrice',
    placeholder: '$10',
    label: 'Max Price',
    type: 'number',
    min: '0',
  },
  distance: {
    name: 'distance',
    label: 'Distance · in miles',
    placeholder: '10',
    type: 'number',
    min: '5',
    max: '50',
  },
};
