export enum Categories {
  Vehicles = 'Vehicles',
  PropertyRentals = 'Property Rentals',
  HomeAndAppliances = 'Home & Appliances',
  Tools = 'Tools',
  Garden = 'Garden',
  Entertainment = 'Entertainment',
  SportsAndOutdoors = 'Sports & Outdoors',
  Electronics = 'Electronics',
  BabyAndKids = 'Baby & Kids',
  JobsAndServices = 'Jobs & Services',
  FashionAndAccessories = 'Fashion & Accessories',
  Other = 'Other',
}

// export const Categories = {
//   Vehicles,
//   PropertyRentals,
//   HomeAndAppliances,
//   Tools,
//   Garden,
//   Entertainment,
//   SportsAndOutdoors,
//   Electronics,
//   BabyAndKids,
//   JobsAndServices,
//   FashionAndAccessories,
//   Other,
// };

export const Subcategories = {
  [Categories.Vehicles]: {
    Car: 'Car',
    Truck: 'Truck',
    Motorcycle: 'Motorcycle',
    Powersport: 'Powersport',
    RVCamper: 'RV & Camper',
    Boat: 'Boat',
    Trailer: 'Trailer',
    Other: 'Other',
  },
  [Categories.PropertyRentals]: {
    Apartment: 'Apartment',
    Condo: 'Condo',
    House: 'House',
    Townhouse: 'Townhouse',
    Room: 'Room',
  },
  [Categories.HomeAndAppliances]: {
    Furniture: 'Furniture',
    Appliances: 'Appliances',
    CookwareAndTableware: 'Cookware & Tableware',
    BeddingAndRugs: 'Bedding & Rugs',
    HomeImprovement: 'Home Improvement',
    Decor: 'Decor',
    Other: 'Other',
  },
  [Categories.Tools]: {
    PowerTools: 'Power Tools',
    HandTools: 'Hand Tools',
    Other: 'Other',
  },
  [Categories.Garden]: {
    Tools: 'Tools',
    Furniture: 'Furniture',
    Other: 'Other',
  },
  [Categories.Entertainment]: {
    VideoGames: 'Video Games',
    BoardGames: 'Board Games',
    Movies: 'Movies',
    Music: 'Music',
    Books: 'Books',
    MusicalInstruments: 'Musical Instruments',
    Other: 'Other',
  },
  [Categories.SportsAndOutdoors]: {
    Bicycle: 'Bicycle',
    SportGear: 'Sport Gear',
    ExerciseEquipment: 'Exercise Equipment',
    CampingGear: 'Camping Gear',
    Other: 'Other',
  },
  [Categories.Electronics]: {
    Phones: 'Phones',
    TVs: 'TVs',
    Computers: 'Computers',
    Cameras: 'Cameras',
    SpeakersAndHeadphones: 'Speakers & Headphones',
    Other: 'Other',
  },
  [Categories.BabyAndKids]: {
    Toys: 'Toys',
    Clothing: 'Clothing',
    Essentials: 'Essentials',
    Other: 'Other',
  },
  [Categories.JobsAndServices]: {
    Jobs: 'Jobs',
    Services: 'Services',
  },
  [Categories.FashionAndAccessories]: {
    HealthAndBeaty: 'Health & Beauty',
    WomenClothing: 'Women Clothing',
    WomenFootwear: 'Women Footwear',
    MenClothing: 'Men Clothing',
    MenFootwear: 'Men Footwear',
    Watches: 'Watches',
    BagsAndLuggages: 'Bags & Luggages',
    Other: 'Other',
  },
  [Categories.Other]: {
    RealEstates: 'Real Estates',
    OfficeSupplies: 'Office Supplies',
    PetSupplies: 'Pet Supplies',
    Other: 'Other',
  },
};
